### ISSUE TITLE
Default Store - Stories unavailable ?

### ISSUE THREAD

**Issue by agouraud** [DantSu/Telmi-Sync#1]
Hi 
First thank you for this great idea and community. 
I wanted to give it a try but it seems the stories from the default store cannot be downloaded. There are 70 stories on the store, but the error message 
`"Failed to download the story" `
is displayed each time we click on the download button.
Any idea ? If there is an issue currently you may want to share that in your readme.md
Thanks!

**Comment by DantSu** [comment]
Try again. It's seems to work again now.

**Comment by agouraud** [comment]
Thank you! Indeed it is now fixed. Many thanks!
For the note you still have 2 or 3 dead links in stories.json - for ex the DL link RnYVFOc0g1ay1ieVh1UjRoWUE
Have a nice week
